### ISSUE TITLE
Don't allow doubles in tour's players list

### ISSUE THREAD

**Issue by fsmosca** [cutechess/cutechess#213]
![image](https://cloud.githubusercontent.com/assets/22366935/26036995/65ca04f6-391c-11e7-90d2-b1d76abdd33f.png)

**Comment by alwey** [comment]
No, actually this is no bug but a feature:

Actually the list is a list of engine configurations rather than engines. You can set up a tournament , say with 3 `Rodent III 0.172 x64 1 CPU` engines. Then modify the entries (button w/ wrench symbol) and set up special parameters (this is using setoption for UCI engines). You can rename these engine settings like EXP1, EXP2  or AGGRO1.

**Comment by fsmosca** [comment]
I know how to setup a proper tournament. I just want cutechess to be smart, not allowing same engine name in the tournament list. This is especially useful when running more than 20 engines where visual examination would already take some effort. Perhaps a box telling the user that there are same engine names in the tournament list after the user presses the OK button would be fine.

**Comment by alwey** [comment]
Yes, a hint of some kind, a button or a dialog box. Indeed, this would be helpful.

**Comment by ilaripih** [comment]
This was done a while ago, forgot to close the issue.
