### ISSUE TITLE
Cutechess writes ECO in PGN instead of FEN

### ISSUE THREAD

**Issue by brtzsnr** [cutechess/cutechess#214]
```
$ cutechess-cli -version
cutechess-cli 0.8.5
Using Qt version 5.7.1
```

Cutechess insert ECO instead of FEN in PGN headers. Older versions did not. I'm using Cutechess to map FEN to game results and I need to original FEN not the ECO positions. Would be possible to add an options to disable the ECO thing?

**Comment by fsmosca** [comment]
Could you describe how you encounter such situation, I will try, if I could duplicate it on latest build.

**Comment by alwey** [comment]
I believe the behaviour of cutechess has not changed recently (at least since version 0.6.0).

If you use an openings file with EPD (or FEN) positions you will get a FEN tag. If you use an openings file with a PGN game from standard initial position you will get an ECO classification. If you use a PGN opening with FEN  position setup you will get a FEN tag.

**Comment by ilaripih** [comment]
This issue is awaiting a response to @fsmosca's question (steps to reproduce the bug).

**Comment by ilaripih** [comment]
Closed due to lack of activity. Feel free to reopen if you find a reproducible bug, eg. missing FEN tag when game was started from custom starting position.
