### ISSUE TITLE
invalid tags in pgn files

### ISSUE THREAD

**Issue by flok99** [cutechess/cutechess#248]
Hi,

It looks like cutechess-cli inserts these kind of tags in pgn -files:

[Variation "Abbazia defense (Classical defense, Modern defense[!])"]

This is very cool but the the [] IN a [] confuses certain pgn readers. So please consider replacing [!] by (!).

**Comment by alwey** [comment]
Hi,
 >[Variation "Abbazia defense (Classical defense, Modern defense[!])"]

this is a line from the ECO code database (e.g. online reference www.365chess.com/eco.php). You can find it also in e.g. PyChess and pgn-extract. I think it would not be wise to tamper with these upstream data.

In my view the problem is more one of the software that gets confused by square brackets within data fields of string type. These are not forbidden by the standard, so the are ok.

**Comment by flok99** [comment]
ok
