### ISSUE TITLE
show nps in kilonodes per second

### ISSUE THREAD

**Issue by ilaripih** [cutechess/cutechess#252]
Instead of nodes per second we should probably use kilonodes per second

**Comment by Nordlandia** [comment]
Do number of tablebase hits suits displaying in decimal unit kilo?

3,000,000 tb hits displayed as 3000K

3,000 tb hits displayed as 3K

**Comment by alwey** [comment]
> Instead of nodes per second we should probably use kilonodes per second

Good idea. I think it is generally good to restrict output to [significant figures](https://en.wikipedia.org/wiki/Significant_figures) and use correct units.

>Do number of tablebase hits suits displaying in decimal unit kilo?
3,250,000 tb hits displayed as 3250K
3,000,000 tb hits displayed as 3000K
3,000 tb hits displayed as 3K

The character k (kilo) is the SI decimal prefix for 1000, from physics.
The prefix Ki (kibi) means 1024, the binary prefix 2**10. from IT.

The uppercase K is used since long, but should be avoided, as it may generate confusion.

The tablebase hits could be given exactly, because they are counted exactly. This is not true for the search speed, because it also depends - in short - on the time interval.

**Comment by Nordlandia** [comment]
@alwey you're right. 

The tablebase hits could but be given exactly, because they are counted exactly.

**Comment by ilaripih** [comment]
Done.
