### ISSUE TITLE
Cute Chess crashed after trying to set an ini file

### ISSUE THREAD

**Issue by fsmosca** [cutechess/cutechess#268]
Fairy-Max has the following feature.

`feature option="Ini File -file ./fmax.ini"`

Cute Chess has built an option on Configure Engine/Advanced tab for this feature. But Cute Chess would crash after attempting to open the ini file.

![image](https://user-images.githubusercontent.com/22366935/29500156-7add2c20-8650-11e7-873d-1410aa2b88d5.png)

I tested this under Window 7, and using Cute Chess  1.0.0 32bit

I use the Fairy-Max 5.0b3 windows exe from the following link.
http://home.hccnet.nl/h.g.muller/CVfairy.html

**Comment by alwey** [comment]
I confirm, cutechess crashed. In my case it was under Linux and with a substantial delay (about half a minute after selecting the ini file and starting a second attempt to configure), and not always, but in the first of five tests.

**Comment by ilaripih** [comment]
This is nasty. The bug happens in `PathLineEdit::browse()`: https://github.com/cutechess/cutechess/blob/master/projects/gui/src/pathlineedit.cpp#L53

The file path editor is a normal `QLineEdit` with a browse button. But when the browse button is clicked (`dlg.exec()`) the `PathLineEdit` widget loses focus and is deleted when the file dialog opens. Then the `m_defaultDir`, `setText()` etc. members point to invalid memory and bad things happen.

A couple of ways to solve this come to my mind:

* Use a file dialog that blocks the event loop so `PathLineEdit` won't be deleted too soon. I don't like this because then any ongoing games will stop too.
* Make the `PathLineEdit` somehow not lose focus when the file dialog is opened. I think it worked like this with previous Qt versions.

**Comment by ilaripih** [comment]
Fixed by a not-so-pretty low-level hack.
