### ISSUE TITLE
Can't quit from cutechess

### ISSUE THREAD

**Issue by gbtami** [cutechess/cutechess#293]
Cutechess enables to add xboard protocol engine without changing the protocol from uci to xboard. The new engine can't be selected when starting a new game. It's not in the list at all.
But.
If I quit from cutechess and start it again, it enables to select such engines. If I start a new engine-engine game (for example crafty vs. fairymax, both left on uci) cutechess doesn't start it and send no message about what was the problem. After this affair it disables to quit from cutechess!

Btw. there is a thread about auto detecting engine protocols starting here http://talkchess.com/forum/viewtopic.php?t=65485&postdays=0&postorder=asc&topic_view=&start=80

**Comment by alwey** [comment]
Confirmed. I also noticed cutechess does not quit under such circumstances, when communication with engine(s) at game start failed. Sadly, the logging does not capture the game start entirely (#142).

Related: #31

**Comment by ilaripih** [comment]
Okay, this is quite serious. If I set an Xboard engine's protocol to UCI and press OK to save changes, there's a `Terminating process of engine Crafty(0)` in the console because the Xboard initialization failed or timed out. But the GUI doesn't show the error at all and happily saves the changes.

A good first step would be to display an error message and keep the engine configuration dialog open without saving changes.

Then solve the problem where a game between two incorrectly configured engines make cutechess hang.

**Comment by ilaripih** [comment]
First step done. Now the only way to reproduce the problem should be hand-editing the `engines.json` file and setting the wrong chess protocol to an engine there.

**Comment by ilaripih** [comment]
Done. Now an error message is displayed if an engine's chess protocol initialization fails (usually due to the 35-second timeout). And the GUI will not hang. I'll make a separate issue about showing a loading indicator while the game is starting.
