### ISSUE TITLE
Failing test in debug mode

### ISSUE THREAD

**Issue by rikardfalkeborn** [cutechess/cutechess#316]
When running in debug mode (tested under Linux, gcc and clang), I see a failing Q_ASSERT.

```
QFATAL : tst_Board::moveStrings(janus castling san1) ASSERT: "!move.isNull()" in file src/board/board.cpp, line 665
FAIL!  : tst_Board::moveStrings(janus castling san1) Received a fatal error.
```
The line in question is:
```
Q_ASSERT(!move.isNull());
```
I was unable to figure out why move is null.

**Comment by alwey** [comment]
@rikardfalkeborn: Could please post the PGN of a game in which this problem occurs?

**Comment by alwey** [comment]
@rikardfalkeborn : Ok, I will look into this.

**Comment by alwey** [comment]
Actually, this has not been a problem when using cutefish in usual way to import games, play games or use a game database. However, there is an inaccuracy in the code. I will provide a fix soon.

Castling notation in Janus Chess is peculiar. 
This is complicated by maintaining Xboard and engine compatibility (please refer to comment in method below):

The assertion fails because JanusBoard::moveFromSanString tries to match a notation like Kb8 or Ki1 to the moves in SAN castling `O-O` and `O-O-O`. It does this by calling its reverse method `sanMoveString`. This is not done in other variants. The latter method test the legality of the move by invoking `makeMove` and `undoMove`. This triggers the assertion when given a null move as argument. And here is the inaccuracy the variable `castlingMove` may be a Null Move. So the remedy is to check this before calling `sanMoveString`.


```
Move JanusBoard::moveFromSanString(const QString& str)
{
	/*
	 * accepts O-O and Kb1/Kb8/Ki1/Ki8 formats for castling
	 * Xboard uses O-O for B-file and Ki1/Ki8 for I-file castling
	 */
	if (str.startsWith("O-O-O"))
		return WesternBoard::moveFromSanString("O-O");
	if (str.startsWith("O-O"))
		return WesternBoard::moveFromSanString("O-O-O");

	if (!str.startsWith(pieceSymbol(King).toUpper()))
		return WesternBoard::moveFromSanString(str);  //main path

	if (hasCastlingRight(sideToMove(), KingSide))
	{
---->		Move castlingMove = WesternBoard::moveFromSanString("O-O");
		if (str == sanMoveString(castlingMove))
			return castlingMove;
	}
	if (hasCastlingRight(sideToMove(), QueenSide))
	{
---->		Move castlingMove = WesternBoard::moveFromSanString("O-O-O");
		if (str == sanMoveString(castlingMove))
			return castlingMove;
	}

	return WesternBoard::moveFromSanString(str); // normal king moves
}
```



excerpt of gdb output:

```
#4  0x0000000000413d26 in Chess::Board::makeMove (this=0x6dcd40, move=..., 
    transition=0x0) at src/board/board.cpp:665
#5  0x0000000000441af8 in Chess::WesternBoard::sanMoveString (this=0x6dcd40, 
    move=...) at src/board/westernboard.cpp:182
#6  0x0000000000428bed in Chess::JanusBoard::sanMoveString (this=0x6dcd40, 
    move=...) at src/board/janusboard.cpp:65
#7  0x0000000000429072 in Chess::JanusBoard::moveFromSanString (this=0x6dcd40, 
    str=...) at src/board/janusboard.cpp:95
#8  0x0000000000412892 in Chess::Board::moveFromString (this=0x6dcd40, str=...)
    at src/board/board.cpp:391
#9  0x000000000040d613 in tst_Board::moveStrings() ()

```
