### ISSUE TITLE
GUI: Chess Board Coordinates

### ISSUE THREAD

**Issue by d3vv** [cutechess/cutechess#356]
Could it possible to do a feature which shows Board Coordinates(ABCDEDGH12345678) into GUI mode?
With this feature cutechess will be a great app for education..

**Comment by alwey** [comment]
+1

**Comment by Ipmanchess** [comment]
I have a other problem..during install a engine you get to see a engine name ,you are free to change the name..you play games with it..and then you see you have used wrong name or want to adjust the engine name to be more correct!
Example..i install Houdini 6.03 ,cutechess takes this name..i change it to Houdini 6.03 x64 bmi2 ..then i say ohh i can choose between Standard or Pro version.. so i rename it to Houdini 6.03 Pro x64 bmi2
But in mean time i have 3 Houdini's in my database and i can't rename them to the last name i want to see?
So,is it possible to add a very simple Rename function into Database so that i have not to replay these games each time!
I can rename very easy in FritzGui ,but for some reason i can't use this pgn database anymore in other tools? for making a crosstable or see some stats..

**Comment by Ipmanchess** [comment]
Thanks..that's what i do now using other tools and is not possible in Cutechess.
And i never said i want to change names in mid-tournament? who will do that?
Is when you open your database and see different names from same engine to rename them to one right name.
I see you are very busy..so thank you for looking to all these requests!!

**Comment by ilaripih** [comment]
Oh okay, I misunderstood. Batch-rename of a player's name in the database view is something that could be implemented.

**Comment by Ipmanchess** [comment]
Great..i know you can't do everything..but you know Cutechess can be the best Gui there is..it could be Arena+FritzGui in one ;)

**Comment by ilaripih** [comment]
Chess board coordinates are now implemented so I'm closing this issue. Any unrelated matters should have their own issue.

**Comment by Ipmanchess** [comment]
Thank you!!

**Comment by d3vv** [comment]
Thank You in Advance
