### ISSUE TITLE
SPRT with big ELO differences

### ISSUE THREAD

**Issue by Hanamuke** [cutechess/cutechess#360]
I was trying to run an experiment using a random play engine (that avoids randomly winning) as an Elo reference. Of course that engine never wins. That prevents the SPRT tests to stop. I understand that you cannot compute the Elo of an engine that always lose, but that shouldn't be a problem for finding the probability of its Elo being outside a threshold. An engine with 100% wins that doesn't pass an SPRT test doesn't sound like it should be the expected behaviour.

**Comment by kiudee** [comment]
This problem comes down to maximum likelihood estimation of the parameters. If you make no assumptions regarding the probability of each of the three classes (W, D, L), you are unable to calculate any parameters before you have seen at least one game in each category. This corresponds to placing a Dirichlet([0, 0, 0]) prior on the parameters, which is improper.
See here for a nice discussion of the effect of the different priors for the Beta distribution:
https://en.wikipedia.org/wiki/Beta_distribution#Haldane's_prior_probability_(Beta(0,0))

One improvement is to "sanitize" the inputs by doing what FishTestWatch is doing:
https://github.com/vondele/FishTestWatch/blob/511dad1bad749249f548110fb185b9a2341bff17/sprt_elo.py#L424-L427
```python
# sanitize
W=max(W,0.001)
D=max(D,0.001)
L=max(L,0.001)
```
This corresponds to assuming a Dirichlet([0.001, 0.001, 0.001]) prior.
This fixes the problem, but still requires many samples until the SPRT check can terminate.

A more principled solution is to use a Dirichlet([0.5, 0.5, 0.5]) prior distribution, which corresponds to [Jeffreys prior](https://en.wikipedia.org/wiki/Jeffreys_prior). This has the advantage that it is invariant to reparametrization and it’s also still a conservative prior which is quickly overruled by actual data.
