### ISSUE TITLE
Feature request: Enable file/directory selection for string type in Advanced tab in cutechess-gui

### ISSUE THREAD

**Issue by Prcuvu** [cutechess/cutechess#478]
For UCI options such as `SyzygyPath`, one may need to specify a path. It is annoying to copy and paste the path from file explorer or terminal. Please consider adding a right-click popup menu containing "Choose file..." and "Choose directory...", which redirects to corresponding file open dialog, to any "string" type value text boxes in the "Advanced" tab of Configure Engine dialog.

**Comment by alwey** [comment]
Actually, most UCI options are engine specific. Speaking of `SyzygyPath`, this can be configured in the GUI once and for all engines via _Tools->Settings-General->"Syzygy tablebases path"_, using the file browser. Is this insufficient?

**Comment by Prcuvu** [comment]
There may be other path-related options that cutechess may not have covered, such as `NalimovPath` (as specified by UCI standard), `GaviotaTbPath`, `Scorpio Egbb Path` and some custom book path. It still stands in demand when encountering such engines.

**Comment by alwey** [comment]
Indeed, `NalimovPath` is specified in the UCI standard. The problem is that in UCI there is no option type "path" to determine that a file path is to be configured. CECP has a path type specification. Perhaps it would be acceptable to infer the specification of a path from the UCI option's name ending on "Path" without being identical to "Path". Then offer selecting paths of the file system. This would not interfere with the UCI spec because this woud only be a convenience hack within the GUI.

**Comment by ilaripih** [comment]
Done
