### ISSUE TITLE
Missing letter in case of promotion considered as illegal move

### ISSUE THREAD

**Issue by rchastain** [cutechess/cutechess#494]
Hello! I imagine that there must be already a discussion somewhere about that issue, but I didn't find it. :)
Cutechess considers the missing letter for promotion as illegal move. OK, this is the protocol. But there are many engines which don't print that letter. It's boring when you would like to do tournaments with these engines.
Why not an option for a tolerant mode regarding the missing letter in case of promotion?
Thank you for your great tool Cute Chess. 🥇 
Regards.
Roland

**Comment by tpoppins** [comment]
Indeed, although the CECP and the UCI protocol specs state the promotion move specify the piece to be promoted to nowhere does it say there that a GUI should abort the game when one of the engines fails to do so. 

Arena and Winboard interpret such moves as implicit promotions to queen and allow the game to continue without any error messages. Incidentally, Winboard's author, H.G. Muller, is one of the two authors of the CECP protocol. If the author of the specs doesn't consider such moves a critical error why is Cute Chess being so overly pedantic about it?

I'm aware of the argument that strict adherence to the specs encourages engines to root out bugs in their programs. But this argument is moot where hundreds of engines no longer in development are concerned. I have over 500 engines (incl. various versions) installed to use in CCRL tests, and of these over 30 do not specify the piece suffix on promotion. So I have to put each and every such engine into a dir of its own, copy WB2UCI or Polyglot files in there and edit their configs individually. 

Tedious, cumbersome and error-prone. Additionally, an extra layer of instability and a potential source of trouble is introduced as some engines, working otherwise fine under CC, have problems with certain adapter versions.

A simple solution would be to treat all promotion moves lacking the piece suffix as promotions to queen, as Winboard, Arena, Polyglot, WB2UCI and probably most other programs do. For specs compatibility purposes there could be a developer mode, initiated with "-debug" or the like on the command line. This solution would be completely transparent to the end user.

Another way to do it would be a "Treat promotions without piece suffix as promotions to queen" checkbox under Options/General which would be selected by default.

I would think that the main purpose of a chess GUI is to make running engines easy, not making their users' lives as hard as possible to meet some abstract ideals.

**Comment by rchastain** [comment]
By the way, I saw today an engine (Adam 3.3 if I remember correctly) which lost on a promotion move with an upper case "Q". But it's the first time that I meet that case.

**Comment by tpoppins** [comment]
You must misremember. Adam 3.3 does print the piece suffix of promotions by White in upper case  but Cute Chess ignores the case.

**Comment by rchastain** [comment]
> You must misremember. Adam 3.3 does print the piece suffix of promotions by White in upper case but Cute Chess ignores the case.

I have tested again, after I read your message, and I confirm the issue.

> Finished game 9 (Adam 3.3 vs Arminius 20170101 [random]): 0-1 {White makes an illegal move: c7d8R}

> cutechess-cli 1.1.0 (2019-01-18 dev build)
> Using Qt version 5.12.1

**Comment by tpoppins** [comment]
Interesting: it treats the case of the underpromotions' suffixes differently? You should probably submit it as a separate issue; the UCI spec doesn't explicitly forbid upper case for promotions.

**Comment by alwey** [comment]
> Arena and Winboard interpret such moves as implicit promotions to queen and allow the game to continue without any error messages. Incidentally, Winboard's author, H.G. Muller, is one of the two authors of the CECP protocol. If the author of the specs doesn't consider such moves a critical error why is Cute Chess being so overly pedantic about it?

 Cutechess supports standard chess and variants - some of them with _optional_  promotions (so a choice is made between a move without promotion and a promotion move), e.g. _Grand Chess_ or _Seirawan Chess_. A move without promotion letter does not represent a promotion move.

> I'm aware of the argument that strict adherence to the specs encourages engine authors to root out bugs in their programs. But this argument is moot where hundreds of engines no longer in development are concerned. I have over 500 engines (incl. various versions) installed to use in CCRL tests, and of these over 30 do not specify the piece suffix on promotion. So I have to put each and every such engine into a dir of its own, copy WB2UCI or Polyglot files in there and edit their configs individually.

Stability of the engine interface is an important factor. I would implement separate `B0rkenUciEngine` and `B0rkenXboardEngine` classes. But then one would not know how the broken engines react to a promotion move by the opponent, would they accept a letter q or not?

**Comment by rchastain** [comment]
> But then one would not know how the broken engines react to a promotion move by the opponent, would they accept a letter q or not?

Thank you for your answer. Yes, good question. I hadn't thought of that problem.

Regards.

Roland

**Comment by tpoppins** [comment]
A groundless fear. Just assume that they do and it will work. Works for nearly every other GUI out there.

**Comment by rchastain** [comment]
I think I was wrong to close the thread. Two years later, it is still annoying not to be able to include certain engines in tournaments for this reason.

@alwey 

Please what is your last word about that question?

**Comment by alwey** [comment]
I already implemented patches to alleviate the inclusion of older engines or to enhance the interoperability. Some of those changes were accepted into the master branch .

But IMO, the suggested change above breaks the implementation, has no good remedy and no merit. Why break cutechess in order to adapt to broken engine implementations?

Some tools like "In-Between" can help to adapt buggy engines in many cases.
