### ISSUE TITLE
Pins ignored for gating moves in S-Chess

### ISSUE THREAD

**Issue by ianfab** [cutechess/cutechess#569]
As a result of https://github.com/ianfab/Fairy-Stockfish/issues/141 I also checked the behavior for gating moves of pieces pinned against the king in cutechess (GUI, did not check in CLI yet), and found that it allows moves that should be treated as illegal:

`r1bqkbn1/pppppp2/2n5/6p1/2B1P3/2P5/PP1P1PP1/RNBQK1Nr[EHeh] w cdfgBCDGQq - 1 6`
illegal moves: Nf3/H, etc.

`r1bqkbn1/pppppp2/8/6p1/Q2nP3/PBP5/1P1P1PP1/RNB1K2r[EHeh] w cdfgBCQq - 1 10`
illegal moves: Kd1/E, Kd1/H

See the game https://www.pychess.org/6f66ytoY for a game including those test positions (before white's move 6 and 10).

**Comment by alwey** [comment]
Thank you for reporting this.
The current behaviour of cutechess is logical, because the king is not exposed to an attack.

As you noted in https://github.com/ianfab/Fairy-Stockfish/issues/141
>This behavior is intentional, since the king can not be in check during the move, but I unfortunately can not find a clear reference for this rule right now. Do you have a reference for your interpretation of the rule?

Same here.

I was not aware of the mentioned rule, too:
>When a piece is moved from its original square, the move must be legal according to the laws of chess; the placement of an undeveloped Hawk or Elephant as part of the initial move to block a check or replace a pinned piece is not sufficient to render legal an otherwise illegal move.

Also, [Wikipedia](https://en.wikipedia.org/wiki/Seirawan_chess) mentions (/wrt gating):
>One cannot use the placing of an elephant or hawk to block check.

So an additional legality check has to be used.
