### ISSUE TITLE
A few questions as for the program cutechess 1.2

### ISSUE THREAD

**Issue by Krzychumag** [cutechess/cutechess#601]
1. After the click on "New Game" and by choice of chess engines I would like to play the resulting match 20 games. 
2. Please write where at the counter I can how many parties mark I am supposed to play and how to turn the side so that each of engines plays white and black - alternately.
3. Where I can mark "Rule of 50 moves to all engines".
4. Why there are no Swiss tournaments.

**Comment by alwey** [comment]
1 and 2. : Use Tournament->New .
The NewTournamentDialog lets you select players, time control, **opening suite** (set up starting positions from FEN, or opening moves from PGN file), opening books, number of **games per encounter** (20), **number of repetitions** (20) , **swap** sides (should be on - this is the default to play alternate colors).

3.: You cannot mark it. It is built into the standard chess rules of cutechess. After 50 full moves without capture or Pawn advance
cutechess will adjudicate a draw.

4.Because nobody has coded and shared it.

**Comment by artoj** [comment]
Ditto.

**Comment by Krzychumag** [comment]
@ alwey - but nonsense you write in the "New Game" option there is no option to play the game amount. Read with understanding - because you do not understand what I am asking.

**Comment by Krzychumag** [comment]
I mean this window.
![New games](https://user-images.githubusercontent.com/30792281/90170137-da495900-dd9f-11ea-964a-a26985d7a706.jpg)

**Comment by alwey** [comment]
@Krzychumag; 

> @ alwey - but nonsense you write in the "New Game" option there is no option to play the game amount.

I would advise you to read and think before writing.
The **"New Game" window is the wrong way to go**, please use the new tournament window instead.

**Comment by Krzychumag** [comment]
**@alwey** - once again read with understanding - I am not asking about the window  " New tournament ".  I asked about the window "New Game". Concentrate on the reading alwey.

**Comment by alwey** [comment]
@Krzychumag : Try getting help from others, I am done.
