### ISSUE TITLE
Allow different time control (or node limits) for each player to enable time odds games

### ISSUE THREAD

**Issue by benwh1** [cutechess/cutechess#619]
I'd like to run an engine tournament where all the players are the same engine, but with differing amounts of search time to see how the strength varies. As far as I can tell, this currently isn't possible because there is only a single time control option in the tournament settings window.

**Comment by alwey** [comment]
I assume you are referring to the GUI and not the CLI, because you can already use per-engine time controls in the CLI. This issue is a duplicate (or subtopic) both of #161 and #413.
.
We already have an active pull-request to upgrade the GUI with split time controls, please see PR #599.

This PR deals with two topics
- Option to use split time controls for White and Black in individual games in the GUI
- Option to use individual time controls in tournaments in the GUI

My  [EXPER1-branch](https://github.com/alwey/cutechess/commit/9cc2af6a8d4a9cc5d049786348b9affbbb175232) also contains this patch among others.

**Comment by alwey** [comment]
This issue is a duplicate (or rather subtopic) of #161 and #413 and discussed in #351 

From #351:
> Time handicap can also be useful for characterisation of engines (e.g. in self play). Note: You can already use time handicaps with the CLI..

.
We already have an active pull-request to upgrade the GUI with split time controls, please see PR #599.

This PR deals with two topics
- Option to use split time controls for White and Black in individual games in the GUI
- Option to use individual time controls in tournaments in the GUI

My  [EXPER1-branch](https://github.com/alwey/cutechess/commit/9cc2af6a8d4a9cc5d049786348b9affbbb175232) also contains this patch among others.

You can add an engine configuration multiple times to a player list. You will have to modify the names in the player list to resolve the duplicates (the tournament needs unique player names) and right-click on the player names to change the time controls individually.


![t1](https://user-images.githubusercontent.com/6425738/92953356-1c25f780-f451-11ea-9d2c-5a9ed0382f46.png) _Engine configuration added to the player list multiple times_


![t2](https://user-images.githubusercontent.com/6425738/92953584-7cb53480-f451-11ea-8145-9d57729a1fe6.png) _Configurations have been renamed to reflect the individual time controls. The time control dialog for the last engine is shown. It has been called by right-clicking the entry and selecting "Edit Time Control"._
