### ISSUE TITLE
PGN game does not load correctly

### ISSUE THREAD

**Issue by DrEsteban** [cutechess/cutechess#650]
**Steps:**

0. Cute Chess version 1.2.0
1. Load game from PGN file:
```
[Event "Let's Play!"]
[Site "Chess.com"]
[Date "2021-01-25"]
[White "Foo"]
[Black "Bar"]
[Result "*"]
[WhiteElo "464"]
[BlackElo "750"]
[TimeControl "1 in 1 day"]
1. Nf3 d6 2. c4 c5 3. Nc3 Bf5 4. e4 Bd7 5. g3 e5 6. d3 Nc6 7. a3 g5 8. Bxg5 Be7 9. Bh4 Nd4 10. b4 Bg4 11. Qa4+ b5 12. Nxd4 bxa4 13. Nc6 *
```

**Expected:**
Game loads accordingly with a display like:
![image](https://user-images.githubusercontent.com/1495037/105649485-5672bd00-5e65-11eb-8ea9-ab45a81e04b0.png)

**Actual:**
Game loads as if from the beginning, and an opening move is made.

**Comment by rwbc** [comment]
Hmmm, how did you load the game? I am asking because in my self compiled version of CuteChess (admittedly a newer branch)
it behaves exactly the way you describe as 'expected'?
I just do Ctrl+V (or Ctrl+H =paste FEN/PGN w or w/o target settings) from the 'Game' menu (after I had copied a game from somewhere).

What I don't like though is, that it adds automatically {book} after each move and removes all already available move comments.

**Comment by DrEsteban** [comment]
I just loaded the game by going to Game > New > Opening suite > Browse. I found that I could get it to advance to the current state of the game by setting the "Depth" field equal to the number of moves made in the PGN file, but that wasn't really what I expected. I expect it to immediately load the board into the latest "state" described by the PGN file.

**Comment by alwey** [comment]
Hello, I have fallen into this trap a few times, too. But the section is called "Opening Suite", not "Load Game".
You can adjust the default value for "Depth" to meet your preference via Tools->Settings->Games.
If empty, enter a dummy name, e.g. a blank into the PGN/EPD file edit. Then set the "Depth" spin box to an appropriate move limit, e. g. 999 plies. Finally remove the dummy name in order to avoid problems and close the dialog by clicking "OK".

HTH.

**Comment by alwey** [comment]
@DrEsteban To load and display games you might also use _Tools->Game Database->Import_. No _Depth_ parameter is involved here.

**Comment by DrEsteban** [comment]
Thanks @alwey!

**Comment by alwey** [comment]
@DrEsteban: You are welcome. If all is OK, may I ask you to close this issue?
