### ISSUE TITLE
replace Gaviota tablebases with Syzygy

### ISSUE THREAD

**Issue by ilaripih** [cutechess/cutechess#68]
Syzygy would be better because:
- Better compression
- 6-men tablebases
- Defects in the GTB code (out-of-bounds reads, resource leaks etc)
- Stockfish already has a good C++ probing implementation that we can use. And its a lot less code than GTB: https://github.com/official-stockfish/Stockfish/tree/master/src/syzygy

**Comment by ilaripih** [comment]
The Stockfish Syzygy probe is actually being rewritten: https://github.com/official-stockfish/Stockfish/tree/syzygy

**Comment by artoj** [comment]
Would it make sense to adapt this code to Qt / C++11 style? I see that it has code dedicated to Win32/Unix compatibility that could be thrown out.

**Comment by artoj** [comment]
It seems that the new code uses C++11.

**Comment by raimarHD** [comment]
Here is another approach to integrate Syzygy into an existing program.
https://github.com/basil00/Fathom
Some chessengines like Arasan use this lib.

**Comment by ilaripih** [comment]
Thanks for letting us know! I like Stockfish's C++ code (closer to most CuteChess code) but Fathom would actually be significantly easier to integrate into CuteChess because we wouldn't have to rewrite any Syzygy code.

**Comment by mcostalba** [comment]
@ilaripih In case you opt to use SF syzygy code, please use this file:

https://github.com/official-stockfish/Stockfish/blob/syzygy/src/syzygy/tbprobe.cpp

and delete all the lines starting from [here](https://github.com/official-stockfish/Stockfish/blob/syzygy/src/syzygy/tbprobe.cpp#L1477) til the EOF. This code has not been updated and is still in the original form, I have not touched it because I planned to completely drop it because hacky and useless.

In you case you just need:

```
void init(const std::string& paths);
WDLScore probe_wdl(Position& pos, ProbeState* result);
int probe_dtz(Position& pos, ProbeState* result);
```

header is [here ](https://github.com/official-stockfish/Stockfish/blob/syzygy/src/syzygy/tbprobe.h)

Probing code is fully tested in parallel with original code to ensure all the calls to both code paths  return same values (tested on many hundreds millions calls over hundreds of endgame positions), and actually does not have a bug that instead is present in the original code.

Finally I think the code properly documents how TB works.

**Comment by mcostalba** [comment]
@ilaripih in case you are interested I can factor the needed code out of SF so to make a kind of library.

**Comment by ilaripih** [comment]
@mcostalba that would be awesome and much appreciated! I really like the new C++11 implementation in Stockfish.

**Comment by mcostalba** [comment]
@ilaripih your welcome!

Here is a slimmed down tree with just the needed files:

https://github.com/mcostalba/Stockfish/tree/tblib/

I have kept original code in the original files, without merging in a single file, this should help debugging in case it is needed.

To see usage please look at main.cpp

Makefile is the original SF one slightly adapted, you may want to use yours so in this case just need to add the new object files (indeed main is needed just to show an example of usage):

```
### Object files
OBJS = bitboard.o main.o movegen.o position.o tbprobe.o
```

Please feel free to ask if anything is not clear.

**Comment by lucasart** [comment]
Taking the entire SF bitboard/position/movegen code seems like a lot of unnecessary bloat. Would it be that hard to modify tbprobe.cpp to use cutechess' own implementation of board and move code ?

**Comment by mcostalba** [comment]
@lucasart  Well, that would be a not trivial sub-project. But if Ilari decides to merge this code, once it is merged I could work on it as a TODO target.

**Comment by ilaripih** [comment]
@mcostalba thanks. I'll add your tb code (along with the necessary Stockfish code) to a new CuteChess branch soon and replace Gaviota with Syzygy. And I agree with @lucasart, it would be nice to use CuteChess' board and move implementation. Our primary focus is on the cutechess-gui 1.0 milestone; the Syzygy stuff can be merged to master later when it's ready.

**Comment by mcostalba** [comment]
@ilaripih ok for me. Thanks.

To avoid introducing bugs I'd suggest to add current tb code, I will _add_ new one so to be called in parallel behind the scenes every time tb are probed, this will ensure that new code is functional equivalent with proved one. Once development is stable enough we can drop the old code. Do you agree with this approach?

BTW I gave a quick look at current TB interface in StandardBoard::tablebaseResult(), indeed I'd think just 'this' (that is a class Board pointer) is needed as argument in new TB API. As long as you have no problems if the TB probing does a makeMove() / undoMove() I can use that object directly, otherwise I would need to make a copy first but it is of course slower.

**Comment by ilaripih** [comment]
That sounds like a good approach. At least the worst bugs can be avoided by making sure our tablebase unit tests pass with a new implementation, and extending them if needed: https://github.com/cutechess/cutechess/blob/master/projects/lib/tests/gtb/tst_gtb.cpp

And yes, it's totally fine and safe to call makeMove() and undoMove() in StandardBoard::tablebaseResult(). You'll just have to make it a non-const function.

**Comment by 0zymandia2** [comment]
> Thanks for letting us know! I like Stockfish's C++ code (closer to most CuteChess code) but Fathom would actually be significantly easier to integrate into CuteChess because we wouldn't have to rewrite any Syzygy code.

In any case, you should thank him for [reminding](http://www.talkchess.com/forum/viewtopic.php?p=649020#649020) you.

Looking forward to this.

**Comment by ilaripih** [comment]
There's a working implementation now. If someone contributes a cleaner C++ implementation I'll happily merge that, but this issue can be closed.
