### ISSUE TITLE
Cutechess on heroku

### ISSUE THREAD

**Issue by iamhajemi** [cutechess/cutechess#713]
Is it possible to run cutechess on heroku? I am gettin this error when I try 
cutechess-cli: error while loading shared libraries: libicui18n.so.60: cannot open shared object file: No such file or directory

**Comment by alwey** [comment]
AFAIK, there have been no reports on installing cutechess on Heroku.
The error message shows that the platform does not provide the internationalisation library which the executable needs. Perhaps you can compile a version from source on (or for) the platform.

**Comment by iamhajemi** [comment]
I can run fishtest on heroku. Its running cuteches also.

**Comment by alwey** [comment]
Good. That is cutechess-cli. And I think this is a statically linked binary.

https://github.com/cutechess/cutechess/wiki/Dynamic-linking
https://github.com/glinscott/fishtest/wiki/Build-cutechess-with-Qt5-static

**Comment by iamhajemi** [comment]
I will try Ubuntu 14.04. But whar is the libcutechess?

**Comment by alwey** [comment]
Libcutechess is the heart of cutechess. When building cutechess-cli or cutechess the library libcutechess is built first. It finally gets linked either statically (libcutechess.a) or dynamically (libcutechess.so) to the respective program.

**Comment by alwey** [comment]
Ubuntu 14.04 is too old. It is even older than my Ubuntu 18.04 and this is already getting to old due requirement of newer Qt versions. I have to retro-patch the sources to compile on my system.

**Comment by artoj** [comment]
We support either Debian Stable or Ubuntu LTS, whichever is the oldest. With the release of Ubuntu 22.04, Debian Stable is older. Both of these ship with Qt 5.15 so that's the minimum we support. Building with older Qt versions will become increasingly harder as we start to use the Qt 5 -> Qt 6 transition methods / classes present in Qt 5.15. Eventually this will lead to dropping Qt 5 support entirely but this won't happen until both Debian Stable and Ubuntu LTS ship Qt 6 which, I guess, will happen in 2 years.
