### ISSUE TITLE
no settings menu to import engines (compiled on arm)

### ISSUE THREAD

**Issue by feftywacky** [cutechess/cutechess#796]
In the image below, there is no "settings" menu under the tools dropdown. As a result I cannot import engines.

I compiled the source code version 1.3.1 according to the documentation. My machine has an Apple M3 chip. Any solution?

![image](https://github.com/cutechess/cutechess/assets/117899896/2fbef961-52e9-4809-ba14-9520650ea24c)

**Comment by tissatussa** [comment]
Are the other menus complete ? Or are they also missing items ?
It's a weird issue, i don't expect anyone has an answer to this.

Do the words in the menus have underlined letters, so you can use them by alt-key combinations ? I don't see any in your screenshot (but i'm not on Apple). In my case the 'Tools' menu can be 'reached' by Alt-o because the first 'o' of the word 'Tools' has an underscore. Same for the submenu item 'Game Database' : its first letter 'G' is underlined, so i can do "Alt-o g" to reach it. And i can reach the submenu item 'Settings' by 'Alt-o s'. Can you ?

Sure, this is a workaround when it works.

**Comment by feftywacky** [comment]
Other menus are complete. There are shortcuts for other menus but the shortcut for settings does not work. 

I'll see if I can run the x64 version on an emulator

**Comment by tissatussa** [comment]
> ..the shortcut for settings does not work..

i doubt it has anything to do with your Apple chip, but it could be .. did you dare to look in the code and find the part which creates the menu items and compare it to the others ? What could be different for the Settings submenu item ? Only thing i sometimes encounter is that a (poorly written) engine can be added but doesn't show up in the engine list when picking one.

**Comment by feftywacky** [comment]
The code is not the issue because I compiled it on windows and is fine. I'll double check the compiler I'm using on macos as it differs from the one I'm using on windows
